/**
 * Dynamic Expo config — replaces app.json so we can inject build-time secrets
 * from environment variables (set locally via .env or via EAS Secrets in CI).
 *
 * EAS Secrets to configure (eas secret:create --scope project):
 *   PKCS12_PASSWORD   — passphrase for client.p12 (generated by scripts/gen_certs.sh)
 *   PI_CA_FINGERPRINT — SHA-256 fingerprint of the Pi CA cert for server pinning
 *                       (run: openssl x509 -in config/certs/ca.crt -fingerprint -sha256 -noout)
 *
 * TLS_ENABLED defaults to "true". Set to "false" in local dev when pointing at
 * an HTTP Pi (no certs generated yet).
 */
export default {
  expo: {
    name: 'airosolve-mobile',
    slug: 'airosolve-mobile',
    version: '1.0.0',
    orientation: 'default',
    icon: './assets/icon.png',
    userInterfaceStyle: 'light',
    newArchEnabled: true,
    splash: {
      image: './assets/splash-icon.png',
      resizeMode: 'contain',
      backgroundColor: '#ffffff',
    },
    ios: {
      supportsTablet: true,
      bundleIdentifier: 'com.airosolve.mobile',
      infoPlist: {
        ITSAppUsesNonExemptEncryption: false,
      },
    },
    android: {
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: '#ffffff',
      },
      edgeToEdgeEnabled: true,
      package: 'com.airosolve.mobile',
    },
    web: {
      favicon: './assets/favicon.png',
    },
    // Values exposed to the app at runtime via expo-constants.
    // NEVER put secrets here that you don't want in the JS bundle —
    // PKCS12_PASSWORD will be in the bundle, which is acceptable for
    // a sideloaded clinical-trial build (not a public App Store release).
    extra: {
      eas: {
        projectId: '3c2d875a-abae-488a-bbe7-686c34698355',
      },
      tlsEnabled: process.env.TLS_ENABLED !== 'false',
      pkcs12Password: process.env.PKCS12_PASSWORD ?? '',
      piCaFingerprint: process.env.PI_CA_FINGERPRINT ?? '',
    },
  },
};
