/**
 * TLS / mTLS configuration for the AiroSolve mobile app.
 *
 * Provides a single `getTlsOptions()` call that returns the options object
 * expected by react-native-ssl-pinning's fetch().  When TLS is disabled
 * (local dev without certs), returns null so the caller can fall back to
 * the standard fetch API.
 *
 * Certificate assets
 * ------------------
 * Place the following files in assets/certs/ before building:
 *
 *   assets/certs/client.p12   — PKCS#12 bundle (client key + cert signed by Pi CA)
 *                               Generated by scripts/gen_certs.sh on the Pi.
 *                               ⚠ Never commit — already in .gitignore (*.p12).
 *
 *   assets/certs/ca.crt       — Pi CA certificate (PEM, for server pinning).
 *                               ⚠ Never commit — already in .gitignore (*.pem / *.crt).
 *
 * The PKCS#12 password is injected at build time from the PKCS12_PASSWORD
 * environment variable (see app.config.js).
 *
 * How to get the CA fingerprint (run on any machine with OpenSSL):
 *   openssl x509 -in config/certs/ca.crt -fingerprint -sha256 -noout \
 *     | sed 's/://g' | cut -d= -f2
 * Set the result as the PI_CA_FINGERPRINT EAS secret (no colons, uppercase).
 */
import Constants from 'expo-constants';

const { tlsEnabled, pkcs12Password, piCaFingerprint } = Constants.expoConfig.extra ?? {};

/**
 * Returns the ssl-pinning options for react-native-ssl-pinning, or null when
 * TLS is disabled (plain HTTP dev mode).
 *
 * @returns {{ sslPinning: object, pkcs12: object } | null}
 */
export function getTlsOptions() {
  if (!tlsEnabled) return null;

  if (!pkcs12Password) {
    console.warn(
      '[tls] TLS is enabled but PKCS12_PASSWORD is empty. ' +
        'Build with the EAS secret set, or disable TLS for local dev ' +
        '(set TLS_ENABLED=false in your environment).',
    );
  }

  return {
    // Server certificate pinning — verifies the Pi is who it claims to be.
    // 'ca' is the filename (without extension) of the cert in assets/certs/.
    sslPinning: {
      certs: ['ca'],
    },

    // Client certificate — proves the app is an authorised AiroSolve client.
    // 'client' is the filename (without extension) of the .p12 in assets/certs/.
    pkcs12: {
      path: 'client',
      password: pkcs12Password,
    },
  };
}

/** True when the app is running in mTLS mode. */
export const isTlsEnabled = Boolean(tlsEnabled);
